// Pure-JS ICS builder — no library.
import type { ScheduleSpec } from "@shared/schema";
import { generateDoses } from "@shared/schedule";

export interface ICSEvent {
  uid: string;
  title: string;
  description: string;
  start: Date;
  end: Date;
  alarmMinutes?: number;
}

function pad(n: number, w = 2) {
  return n.toString().padStart(w, "0");
}

function formatDateICS(d: Date): string {
  // UTC with Z suffix
  return (
    d.getUTCFullYear().toString() +
    pad(d.getUTCMonth() + 1) +
    pad(d.getUTCDate()) +
    "T" +
    pad(d.getUTCHours()) +
    pad(d.getUTCMinutes()) +
    pad(d.getUTCSeconds()) +
    "Z"
  );
}

function escapeText(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/\n/g, "\\n")
    .replace(/,/g, "\\,")
    .replace(/;/g, "\\;");
}

export function buildICS(events: ICSEvent[], calName: string): string {
  const lines: string[] = [];
  lines.push("BEGIN:VCALENDAR");
  lines.push("VERSION:2.0");
  lines.push("PRODID:-//Peptide Calculator//EN");
  lines.push("CALSCALE:GREGORIAN");
  lines.push(`X-WR-CALNAME:${escapeText(calName)}`);
  for (const ev of events) {
    lines.push("BEGIN:VEVENT");
    lines.push(`UID:${ev.uid}`);
    lines.push(`DTSTAMP:${formatDateICS(new Date())}`);
    lines.push(`DTSTART:${formatDateICS(ev.start)}`);
    lines.push(`DTEND:${formatDateICS(ev.end)}`);
    lines.push(`SUMMARY:${escapeText(ev.title)}`);
    lines.push(`DESCRIPTION:${escapeText(ev.description)}`);
    if (ev.alarmMinutes && ev.alarmMinutes > 0) {
      lines.push("BEGIN:VALARM");
      lines.push("ACTION:DISPLAY");
      lines.push(`DESCRIPTION:${escapeText(ev.title)}`);
      lines.push(`TRIGGER:-PT${ev.alarmMinutes}M`);
      lines.push("END:VALARM");
    }
    lines.push("END:VEVENT");
  }
  lines.push("END:VCALENDAR");
  return lines.join("\r\n");
}

export function downloadICS(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Expand a stack item into dose events over a date range.
export function expandDoseEvents(params: {
  peptideName: string;
  units: number;
  stackName: string;
  stackNotes?: string;
  frequency: string; // daily | eod | weekly | twice-weekly | 3x-weekly | prn
  timeOfDay: string; // HH:MM
  startDate: Date;
  durationDays: number;
  uidPrefix: string;
}): ICSEvent[] {
  const {
    peptideName,
    units,
    stackName,
    stackNotes,
    frequency,
    timeOfDay,
    startDate,
    durationDays,
    uidPrefix,
  } = params;

  const [hh, mm] = timeOfDay.split(":").map(Number);
  const events: ICSEvent[] = [];

  const intervalDays = (() => {
    switch (frequency) {
      case "daily":
        return 1;
      case "eod":
        return 2;
      case "twice-weekly":
        return 3; // approximate — Mon/Thu pattern
      case "3x-weekly":
        return 2; // approximate
      case "weekly":
        return 7;
      case "prn":
        return 0; // single event
      default:
        return 1;
    }
  })();

  const disclaimer =
    "This schedule was generated by a mathematical tool. NOT medical advice. Consult your physician.";
  const description = `${stackName}\n${stackNotes ?? ""}\n\n${disclaimer}`;

  if (frequency === "prn") {
    const start = new Date(startDate);
    start.setHours(hh || 8, mm || 0, 0, 0);
    const end = new Date(start);
    end.setMinutes(end.getMinutes() + 15);
    events.push({
      uid: `${uidPrefix}-0@peptidecalc`,
      title: `${peptideName} — ${units.toFixed(1)} units (PRN)`,
      description,
      start,
      end,
      alarmMinutes: 15,
    });
    return events;
  }

  let dayOffset = 0;
  let idx = 0;
  while (dayOffset < durationDays) {
    const d = new Date(startDate);
    d.setDate(d.getDate() + dayOffset);
    d.setHours(hh || 8, mm || 0, 0, 0);
    const end = new Date(d);
    end.setMinutes(end.getMinutes() + 15);
    events.push({
      uid: `${uidPrefix}-${idx}@peptidecalc`,
      title: `${peptideName} — ${units.toFixed(1)} units`,
      description,
      start: d,
      end,
      alarmMinutes: 15,
    });
    dayOffset += intervalDays;
    idx += 1;
    if (idx > 2000) break; // safety
  }
  return events;
}

// New schedule-spec-driven expansion — uses generateDoses() for full 7-type support.
export function expandDoseEventsFromSchedule(params: {
  peptideName: string;
  units: number;
  stackName: string;
  stackNotes?: string;
  spec: ScheduleSpec;
  uidPrefix: string;
}): ICSEvent[] {
  const { peptideName, units, stackName, stackNotes, spec, uidPrefix } = params;
  const disclaimer =
    "This schedule was generated by a mathematical tool. NOT medical advice. Consult your physician.";
  const description = `${stackName}\n${stackNotes ?? ""}\n\n${disclaimer}`;

  if (spec.type === "prn") {
    const start = new Date(`${spec.startDate}T${spec.timesOfDay?.[0] ?? "09:00"}:00`);
    const end = new Date(start);
    end.setMinutes(end.getMinutes() + 15);
    return [
      {
        uid: `${uidPrefix}-0@peptidecalc`,
        title: `${peptideName} — ${units.toFixed(1)} units (PRN)`,
        description,
        start,
        end,
        alarmMinutes: 15,
      },
    ];
  }

  const doseTimestamps = generateDoses(spec);
  return doseTimestamps.slice(0, 2000).map((ts, idx) => {
    const start = new Date(ts);
    const end = new Date(ts + 15 * 60 * 1000);
    return {
      uid: `${uidPrefix}-${idx}@peptidecalc`,
      title: `${peptideName} — ${units.toFixed(1)} units`,
      description,
      start,
      end,
      alarmMinutes: 15,
    };
  });
}
